version: '3.8'

services:
  faq-agent:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=postgres
      - DB_NAME=faq_db
      - DB_USER=faq_user
      - DB_PASSWORD=faq_password
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ENVIRONMENT=development
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./db:/app/db

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=faq_user
      - POSTGRES_PASSWORD=faq_password
      - POSTGRES_DB=faq_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U faq_user -d faq_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: